name: Docker Python

on:
  workflow_dispatch:
  schedule:
    - cron: "15 */1 * * *"
  push:
    branches: ["main"]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # max-parallel: 3
      matrix:
        id: [1,2,3]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker
        run: docker build -t bro .

      - name: Run Docker
        env:
          URL_BROWSER: ${{ secrets.URL_BROWSER }}
          URL: ${{ secrets.URL }}
          MINUTOS: ${{ secrets.MINUTOS }}
          NUM_BROWSERS: ${{ secrets.NUM_BROWSERS }}
          EMAIL: ${{ secrets.EMAIL }}
          SENHA: ${{ secrets.SENHA }}
        timeout-minutes: 59
        continue-on-error: true
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/app" \
            -e URL_BROWSER="$URL_BROWSER" \
            -e URL="$URL" \
            -e MINUTOS="$MINUTOS" \
            -e NUM_BROWSERS="$NUM_BROWSERS" \
            -e EMAIL="$EMAIL" \
            -e SENHA="$SENHA" \
            bro

      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: "*.png"
