name: Test IP Matrix
on:
  workflow_dispatch:

jobs:
  test-ip:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        id: [1,2,3]

    steps:
      - name: Show ID
        run: echo "Job ID: ${{ matrix.id }}"

      - name: Show IP
        run: curl -s https://ipinfo.io/ip
